version: '3.5'

services:
  zabbixdb:
    image: mysql:8.0-oracle
    restart: always
    env_file: .env_vars
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    networks:
      zbx_net:

  zabbixserver:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    restart: always
    ports:
      - "10051:10051"
    env_file: .env_vars
    environment:
      - ZBX_ENABLE_SNMP_TRAPS=true
    volumes:
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    depends_on:
      - zabbixdb
    networks:
      zbx_net:

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    restart: always
    ports:
      - "80:8080"
    env_file: .env_vars
    depends_on:
      - zabbixdb
      - zabbixserver
    networks:
      zbx_net:

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    restart: always
    ports:
      - "162:1162/udp"
    volumes:
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    networks:
      zbx_net:

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      zbx_net:

networks:
  zbx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.233.0/24

volumes:
  grafana_storage:
